image: node:8

services:
  - neo4j

before_script:
  - npm install

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

# Run tests with coverage reporting (gitlab will regex parse)
Test:
  script:
    - npm run coverage
  artifacts:
    paths:
      - coverage/